### ISSUE TITLE
bosh-upload-stemcell-from-cf-deployment task does not upload windows stemcell

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/cf-deployment-concourse-tasks#54]
We have an environment that requires a windows diego cell, however the bosh-upload-stemcell-from-cf-deployment/task does not upload the windows stemcell.

Is there a way to get around this that doesn't involve uploading it manually each time there is an updated stemcell?

**Comment by dsabeti** [comment]
Hey @apoydence. We have a much less intelligent task [in our runtime-ci repo](https://github.com/cloudfoundry/runtime-ci/tree/master/scripts/ci/bosh-upload-stemcell) that uploads a stemcell from a local file, as opposed to constructing a [bosh.io url for downloading/uploading the stemcell](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/master/bosh-upload-stemcell-from-cf-deployment/task#L35-L67). 

We originally did this because bosh.io was not hosting windows stemcells at the time; even still, it only supports GCP, AWS, and Azure, while our task offers support for bosh-lite and vSphere as well. I'll use the Github issue as a story to investigate what it would take to update the task to support windows cells as well.

**Comment by anEXPer** [comment]
I have reached into runtime-ci for your upload task for windows. I put a comment on what appears to be the tracker story associated with this issue (though that linkage is broken from the tracker side, maybe?) but I figured I'd come by here and mark my need, too.

**Comment by jvshahid** [comment]
Is this still relevant ? The diego team started using [bosh-upload-stemcells task](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/f642de6290379669f62af9f989897d5974172bd0/bosh-upload-stemcells/task) and we haven't noticed anything wrong with the task so far. This could be due to the fact that the stemcell is already present on the director.

**Comment by anEXPer** [comment]
I'd consider this done - the upload-stemcells task works explicitly for this, as long as you provide an ops file that adds the windows stemcell.

**Comment by apoydence** [comment]
I'm going to close it. If we bump into issues down the road I'll reopen it.
