### ISSUE TITLE
[Feature request]Ability to specify flakeAttempts in run-cats

### ISSUE THREAD

**Issue by norshtein** [cloudfoundry/cf-deployment-concourse-tasks#62]
Sometimes the environment might be fragile, it would be useful to be able to manually set `flakeAttempts` in [run-cats](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/master/run-cats/task#L35) to make ginkgo try more times.

**Comment by dsabeti** [comment]
Hi @norshtein. We thought about exposing this feature exactly as you've described. Ultimately, we decided against it because we don't want to "train" people running CATs to simply increase the flakeAttempts whenever there's a CATs failure. 

We're hoping to address CATs flakiness in a more direct way sometime soon. If you look in our backlog, we have some [stories](https://www.pivotaltracker.com/story/show/151264450) to start measuring CATs flakiness so we can diagnose the root cause.

**Comment by norshtein** [comment]
Hi @dsabeti , thanks for explanation, I'm looking forward to the improvement.
