### ISSUE TITLE
collect-ops-files task should create $BASE_OPS_FILES_DIR

### ISSUE THREAD

**Issue by genevieve** [cloudfoundry/cf-deployment-concourse-tasks#91]
In the collect-ops-files task, we fail if the specified dir does not exist: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/53c79a617ee3b6ced6e4ba3f9c6d77c6b0886728/collect-ops-files/task#L4-L7

In the collect-ops-files task.yml, there is a comment that this path/directory will be created if it does not exist: 
https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/53c79a617ee3b6ced6e4ba3f9c6d77c6b0886728/collect-ops-files/task.yml#L24-L25

I wanted to understand if the comment should be updated or the directory should be created if it does not exist.

**Comment by davewalter** [comment]
Hi @genevieve,

Thanks for bringing this to our attention. In my mind, it doesn't make much sense to create the BASE_OPS_FILE_DIR if it doesn't exist, since that is where the existing ops-files will be copied from, so I have updated the comment in the task.yml to better reflect reality. Here is the updated comment: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/e0d55448ad29aa8c265f39279898c1fb46bac21f/collect-ops-files/task.yml#L24

Regards,
Dave

**Comment by genevieve** [comment]
Cool!
